//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Playground.Models.Skanetrafiken
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
    public partial class GetDepartureArrivalResult
    {

        private int codeField;

        private string messageField;

        private GetDepartureArrivalResultLine[] linesField;

        private GetDepartureArrivalResultStopAreaData stopAreaDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Line", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetDepartureArrivalResultLine[] Lines
        {
            get
            {
                return this.linesField;
            }
            set
            {
                this.linesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetDepartureArrivalResultStopAreaData StopAreaData
        {
            get
            {
                return this.stopAreaDataField;
            }
            set
            {
                this.stopAreaDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetDepartureArrivalResultLine
    {

        private string nameField;

        private int noField;

        private System.DateTime journeyDateTimeField;

        private bool isTimingPointField;

        private string stopPointField;

        private int lineTypeIdField;

        private string lineTypeNameField;

        private string towardsField;

        private GetDepartureArrivalResultLineFootNote[] footNotesField;

        private GetDepartureArrivalResultLineRealTimeInfo[] realTimeField;

        private int trainNoField;

        private GetDepartureArrivalResultLineDeviation[] deviationsField;

        private int runNoField;

        private bool runNoFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime JourneyDateTime
        {
            get
            {
                return this.journeyDateTimeField;
            }
            set
            {
                this.journeyDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsTimingPoint
        {
            get
            {
                return this.isTimingPointField;
            }
            set
            {
                this.isTimingPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StopPoint
        {
            get
            {
                return this.stopPointField;
            }
            set
            {
                this.stopPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int LineTypeId
        {
            get
            {
                return this.lineTypeIdField;
            }
            set
            {
                this.lineTypeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineTypeName
        {
            get
            {
                return this.lineTypeNameField;
            }
            set
            {
                this.lineTypeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Towards
        {
            get
            {
                return this.towardsField;
            }
            set
            {
                this.towardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FootNote", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetDepartureArrivalResultLineFootNote[] FootNotes
        {
            get
            {
                return this.footNotesField;
            }
            set
            {
                this.footNotesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RealTimeInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetDepartureArrivalResultLineRealTimeInfo[] RealTime
        {
            get
            {
                return this.realTimeField;
            }
            set
            {
                this.realTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TrainNo
        {
            get
            {
                return this.trainNoField;
            }
            set
            {
                this.trainNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Deviation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetDepartureArrivalResultLineDeviation[] Deviations
        {
            get
            {
                return this.deviationsField;
            }
            set
            {
                this.deviationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RunNo
        {
            get
            {
                return this.runNoField;
            }
            set
            {
                this.runNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunNoSpecified
        {
            get
            {
                return this.runNoFieldSpecified;
            }
            set
            {
                this.runNoFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetDepartureArrivalResultLineFootNote
    {

        private string indexField;

        private string textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetDepartureArrivalResultLineRealTimeInfo
    {

        private string newDepPointField;

        private string newArrPointField;

        private int depTimeDeviationField;

        private bool depTimeDeviationFieldSpecified;

        private RealTimeAffect depDeviationAffectField;

        private bool depDeviationAffectFieldSpecified;

        private int arrTimeDeviationField;

        private bool arrTimeDeviationFieldSpecified;

        private RealTimeAffect arrDeviationAffectField;

        private bool arrDeviationAffectFieldSpecified;

        private bool canceledField;

        private bool canceledFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NewDepPoint
        {
            get
            {
                return this.newDepPointField;
            }
            set
            {
                this.newDepPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NewArrPoint
        {
            get
            {
                return this.newArrPointField;
            }
            set
            {
                this.newArrPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DepTimeDeviation
        {
            get
            {
                return this.depTimeDeviationField;
            }
            set
            {
                this.depTimeDeviationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepTimeDeviationSpecified
        {
            get
            {
                return this.depTimeDeviationFieldSpecified;
            }
            set
            {
                this.depTimeDeviationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealTimeAffect DepDeviationAffect
        {
            get
            {
                return this.depDeviationAffectField;
            }
            set
            {
                this.depDeviationAffectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepDeviationAffectSpecified
        {
            get
            {
                return this.depDeviationAffectFieldSpecified;
            }
            set
            {
                this.depDeviationAffectFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ArrTimeDeviation
        {
            get
            {
                return this.arrTimeDeviationField;
            }
            set
            {
                this.arrTimeDeviationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArrTimeDeviationSpecified
        {
            get
            {
                return this.arrTimeDeviationFieldSpecified;
            }
            set
            {
                this.arrTimeDeviationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealTimeAffect ArrDeviationAffect
        {
            get
            {
                return this.arrDeviationAffectField;
            }
            set
            {
                this.arrDeviationAffectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArrDeviationAffectSpecified
        {
            get
            {
                return this.arrDeviationAffectFieldSpecified;
            }
            set
            {
                this.arrDeviationAffectFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Canceled
        {
            get
            {
                return this.canceledField;
            }
            set
            {
                this.canceledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanceledSpecified
        {
            get
            {
                return this.canceledFieldSpecified;
            }
            set
            {
                this.canceledFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetDepartureArrivalResultLineDeviation
    {

        private GetDepartureArrivalResultLineDeviationDeviationScope[] deviationScopesField;

        private string publicNoteField;

        private string headerField;

        private string detailsField;

        private string summaryField;

        private string shortTextField;

        private int importanceField;

        private int influenceField;

        private int urgencyField;

        private GetDepartureArrivalResultLineDeviationWebLink[] webLinksField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DeviationScope", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetDepartureArrivalResultLineDeviationDeviationScope[] DeviationScopes
        {
            get
            {
                return this.deviationScopesField;
            }
            set
            {
                this.deviationScopesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PublicNote
        {
            get
            {
                return this.publicNoteField;
            }
            set
            {
                this.publicNoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShortText
        {
            get
            {
                return this.shortTextField;
            }
            set
            {
                this.shortTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Importance
        {
            get
            {
                return this.importanceField;
            }
            set
            {
                this.importanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Influence
        {
            get
            {
                return this.influenceField;
            }
            set
            {
                this.influenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Urgency
        {
            get
            {
                return this.urgencyField;
            }
            set
            {
                this.urgencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WebLink", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetDepartureArrivalResultLineDeviationWebLink[] WebLinks
        {
            get
            {
                return this.webLinksField;
            }
            set
            {
                this.webLinksField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetDepartureArrivalResultLineDeviationDeviationScope
    {

        private ScopeAttributeType[] scopeAttributeField;

        private System.DateTime fromDateTimeField;

        private System.DateTime toDateTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScopeAttribute", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ScopeAttributeType[] ScopeAttribute
        {
            get
            {
                return this.scopeAttributeField;
            }
            set
            {
                this.scopeAttributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime FromDateTime
        {
            get
            {
                return this.fromDateTimeField;
            }
            set
            {
                this.fromDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ToDateTime
        {
            get
            {
                return this.toDateTimeField;
            }
            set
            {
                this.toDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetDepartureArrivalResultLineDeviationWebLink
    {

        private string uRLField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetDepartureArrivalResultStopAreaData
    {

        private string nameField;

        private int xField;

        private int yField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }
}
