//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Playground.Models.Skanetrafiken
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
    public partial class GetJourneyResult
    {

        private int codeField;

        private string messageField;

        private string journeyResultKeyField;

        private GetJourneyResultJourney[] journeysField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JourneyResultKey
        {
            get
            {
                return this.journeyResultKeyField;
            }
            set
            {
                this.journeyResultKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Journey", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetJourneyResultJourney[] Journeys
        {
            get
            {
                return this.journeysField;
            }
            set
            {
                this.journeysField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourney
    {

        private int sequenceNoField;

        private System.DateTime depDateTimeField;

        private System.DateTime arrDateTimeField;

        private int depWalkDistField;

        private int arrWalkDistField;

        private int noOfChangesField;

        private bool guaranteedField;

        private int cO2factorField;

        private int noOfZonesField;

        private string priceZoneListField;

        private string fareTypeField;

        private GetJourneyResultJourneyPriceInfo[] pricesField;

        private string journeyKeyField;

        private GetJourneyResultJourneyRouteLink[] routeLinksField;

        private int distanceField;

        private float cO2valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SequenceNo
        {
            get
            {
                return this.sequenceNoField;
            }
            set
            {
                this.sequenceNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DepDateTime
        {
            get
            {
                return this.depDateTimeField;
            }
            set
            {
                this.depDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ArrDateTime
        {
            get
            {
                return this.arrDateTimeField;
            }
            set
            {
                this.arrDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DepWalkDist
        {
            get
            {
                return this.depWalkDistField;
            }
            set
            {
                this.depWalkDistField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ArrWalkDist
        {
            get
            {
                return this.arrWalkDistField;
            }
            set
            {
                this.arrWalkDistField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NoOfChanges
        {
            get
            {
                return this.noOfChangesField;
            }
            set
            {
                this.noOfChangesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Guaranteed
        {
            get
            {
                return this.guaranteedField;
            }
            set
            {
                this.guaranteedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CO2factor
        {
            get
            {
                return this.cO2factorField;
            }
            set
            {
                this.cO2factorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NoOfZones
        {
            get
            {
                return this.noOfZonesField;
            }
            set
            {
                this.noOfZonesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriceZoneList
        {
            get
            {
                return this.priceZoneListField;
            }
            set
            {
                this.priceZoneListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FareType
        {
            get
            {
                return this.fareTypeField;
            }
            set
            {
                this.fareTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PriceInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetJourneyResultJourneyPriceInfo[] Prices
        {
            get
            {
                return this.pricesField;
            }
            set
            {
                this.pricesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JourneyKey
        {
            get
            {
                return this.journeyKeyField;
            }
            set
            {
                this.journeyKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RouteLink", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetJourneyResultJourneyRouteLink[] RouteLinks
        {
            get
            {
                return this.routeLinksField;
            }
            set
            {
                this.routeLinksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float CO2value
        {
            get
            {
                return this.cO2valueField;
            }
            set
            {
                this.cO2valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyPriceInfo
    {

        private string priceTypeField;

        private float priceField;

        private float vATField;

        private string journeyTicketKeyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriceType
        {
            get
            {
                return this.priceTypeField;
            }
            set
            {
                this.priceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float VAT
        {
            get
            {
                return this.vATField;
            }
            set
            {
                this.vATField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JourneyTicketKey
        {
            get
            {
                return this.journeyTicketKeyField;
            }
            set
            {
                this.journeyTicketKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLink
    {

        private string routeLinkKeyField;

        private System.DateTime depDateTimeField;

        private bool depIsTimingPointField;

        private System.DateTime arrDateTimeField;

        private bool arrIsTimingPointField;

        private bool callTripField;

        private GetJourneyResultJourneyRouteLinkPriceZone[] priceZonesField;

        private GetJourneyResultJourneyRouteLinkRealTime realTimeField;

        private GetJourneyResultJourneyRouteLinkFrom fromField;

        private GetJourneyResultJourneyRouteLinkTO toField;

        private GetJourneyResultJourneyRouteLinkLine lineField;

        private GetJourneyResultJourneyRouteLinkDeviation[] deviationsField;

        private int accessibilityField;

        private bool accessibilityFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteLinkKey
        {
            get
            {
                return this.routeLinkKeyField;
            }
            set
            {
                this.routeLinkKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DepDateTime
        {
            get
            {
                return this.depDateTimeField;
            }
            set
            {
                this.depDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DepIsTimingPoint
        {
            get
            {
                return this.depIsTimingPointField;
            }
            set
            {
                this.depIsTimingPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ArrDateTime
        {
            get
            {
                return this.arrDateTimeField;
            }
            set
            {
                this.arrDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ArrIsTimingPoint
        {
            get
            {
                return this.arrIsTimingPointField;
            }
            set
            {
                this.arrIsTimingPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CallTrip
        {
            get
            {
                return this.callTripField;
            }
            set
            {
                this.callTripField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PriceZone", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetJourneyResultJourneyRouteLinkPriceZone[] PriceZones
        {
            get
            {
                return this.priceZonesField;
            }
            set
            {
                this.priceZonesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetJourneyResultJourneyRouteLinkRealTime RealTime
        {
            get
            {
                return this.realTimeField;
            }
            set
            {
                this.realTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetJourneyResultJourneyRouteLinkFrom From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetJourneyResultJourneyRouteLinkTO To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetJourneyResultJourneyRouteLinkLine Line
        {
            get
            {
                return this.lineField;
            }
            set
            {
                this.lineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Deviation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetJourneyResultJourneyRouteLinkDeviation[] Deviations
        {
            get
            {
                return this.deviationsField;
            }
            set
            {
                this.deviationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Accessibility
        {
            get
            {
                return this.accessibilityField;
            }
            set
            {
                this.accessibilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessibilitySpecified
        {
            get
            {
                return this.accessibilityFieldSpecified;
            }
            set
            {
                this.accessibilityFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkPriceZone
    {

        private int idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkRealTime
    {

        private GetJourneyResultJourneyRouteLinkRealTimeRealTimeInfo[] realTimeInfoField;

        private GetJourneyResultJourneyRouteLinkRealTimeRealTimeRoadInfo[] realTimeRoadInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RealTimeInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetJourneyResultJourneyRouteLinkRealTimeRealTimeInfo[] RealTimeInfo
        {
            get
            {
                return this.realTimeInfoField;
            }
            set
            {
                this.realTimeInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RealTimeRoadInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetJourneyResultJourneyRouteLinkRealTimeRealTimeRoadInfo[] RealTimeRoadInfo
        {
            get
            {
                return this.realTimeRoadInfoField;
            }
            set
            {
                this.realTimeRoadInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkRealTimeRealTimeInfo
    {

        private string newDepPointField;

        private string newArrPointField;

        private int depTimeDeviationField;

        private bool depTimeDeviationFieldSpecified;

        private RealTimeAffect depDeviationAffectField;

        private bool depDeviationAffectFieldSpecified;

        private int arrTimeDeviationField;

        private bool arrTimeDeviationFieldSpecified;

        private RealTimeAffect arrDeviationAffectField;

        private bool arrDeviationAffectFieldSpecified;

        private bool canceledField;

        private bool canceledFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NewDepPoint
        {
            get
            {
                return this.newDepPointField;
            }
            set
            {
                this.newDepPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NewArrPoint
        {
            get
            {
                return this.newArrPointField;
            }
            set
            {
                this.newArrPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DepTimeDeviation
        {
            get
            {
                return this.depTimeDeviationField;
            }
            set
            {
                this.depTimeDeviationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepTimeDeviationSpecified
        {
            get
            {
                return this.depTimeDeviationFieldSpecified;
            }
            set
            {
                this.depTimeDeviationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealTimeAffect DepDeviationAffect
        {
            get
            {
                return this.depDeviationAffectField;
            }
            set
            {
                this.depDeviationAffectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepDeviationAffectSpecified
        {
            get
            {
                return this.depDeviationAffectFieldSpecified;
            }
            set
            {
                this.depDeviationAffectFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ArrTimeDeviation
        {
            get
            {
                return this.arrTimeDeviationField;
            }
            set
            {
                this.arrTimeDeviationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArrTimeDeviationSpecified
        {
            get
            {
                return this.arrTimeDeviationFieldSpecified;
            }
            set
            {
                this.arrTimeDeviationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealTimeAffect ArrDeviationAffect
        {
            get
            {
                return this.arrDeviationAffectField;
            }
            set
            {
                this.arrDeviationAffectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArrDeviationAffectSpecified
        {
            get
            {
                return this.arrDeviationAffectFieldSpecified;
            }
            set
            {
                this.arrDeviationAffectFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Canceled
        {
            get
            {
                return this.canceledField;
            }
            set
            {
                this.canceledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanceledSpecified
        {
            get
            {
                return this.canceledFieldSpecified;
            }
            set
            {
                this.canceledFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkRealTimeRealTimeRoadInfo
    {

        private string roadField;

        private RoadInfoType reasonField;

        private string infoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Road
        {
            get
            {
                return this.roadField;
            }
            set
            {
                this.roadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RoadInfoType Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public enum RoadInfoType
    {

        /// <remarks/>
        UNKNOWN,

        /// <remarks/>
        WEATHER,

        /// <remarks/>
        ROAD_ACCIDENT,

        /// <remarks/>
        ROAD_WORK,

        /// <remarks/>
        ROAD_CONDITION,

        /// <remarks/>
        EVENT,

        /// <remarks/>
        HOLIDAY,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkFrom
    {

        private int idField;

        private string nameField;

        private string stopPointField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StopPoint
        {
            get
            {
                return this.stopPointField;
            }
            set
            {
                this.stopPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkTO
    {

        private int idField;

        private string nameField;

        private string stopPointField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StopPoint
        {
            get
            {
                return this.stopPointField;
            }
            set
            {
                this.stopPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkLine
    {

        private string nameField;

        private int noField;

        private bool noFieldSpecified;

        private int runNoField;

        private bool runNoFieldSpecified;

        private int lineTypeIdField;

        private string lineTypeNameField;

        private int transportModeIdField;

        private string transportModeNameField;

        private int trainNoField;

        private bool trainNoFieldSpecified;

        private string towardsField;

        private int operatorIdField;

        private bool operatorIdFieldSpecified;

        private string operatorNameField;

        private GetJourneyResultJourneyRouteLinkLineFootNote[] footNotesField;

        private GetJourneyResultJourneyRouteLinkLinePointOnRouteLink[] pointsOnRouteLinkField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoSpecified
        {
            get
            {
                return this.noFieldSpecified;
            }
            set
            {
                this.noFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RunNo
        {
            get
            {
                return this.runNoField;
            }
            set
            {
                this.runNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunNoSpecified
        {
            get
            {
                return this.runNoFieldSpecified;
            }
            set
            {
                this.runNoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int LineTypeId
        {
            get
            {
                return this.lineTypeIdField;
            }
            set
            {
                this.lineTypeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineTypeName
        {
            get
            {
                return this.lineTypeNameField;
            }
            set
            {
                this.lineTypeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TransportModeId
        {
            get
            {
                return this.transportModeIdField;
            }
            set
            {
                this.transportModeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransportModeName
        {
            get
            {
                return this.transportModeNameField;
            }
            set
            {
                this.transportModeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TrainNo
        {
            get
            {
                return this.trainNoField;
            }
            set
            {
                this.trainNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrainNoSpecified
        {
            get
            {
                return this.trainNoFieldSpecified;
            }
            set
            {
                this.trainNoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Towards
        {
            get
            {
                return this.towardsField;
            }
            set
            {
                this.towardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int OperatorId
        {
            get
            {
                return this.operatorIdField;
            }
            set
            {
                this.operatorIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatorIdSpecified
        {
            get
            {
                return this.operatorIdFieldSpecified;
            }
            set
            {
                this.operatorIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OperatorName
        {
            get
            {
                return this.operatorNameField;
            }
            set
            {
                this.operatorNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FootNote", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetJourneyResultJourneyRouteLinkLineFootNote[] FootNotes
        {
            get
            {
                return this.footNotesField;
            }
            set
            {
                this.footNotesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PointOnRouteLink", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetJourneyResultJourneyRouteLinkLinePointOnRouteLink[] PointsOnRouteLink
        {
            get
            {
                return this.pointsOnRouteLinkField;
            }
            set
            {
                this.pointsOnRouteLinkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkLineFootNote
    {

        private string indexField;

        private string textField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkLinePointOnRouteLink
    {

        private int idField;

        private string nameField;

        private string stopPointField;

        private System.DateTime arrDateTimeField;

        private bool arrIsTimingPointField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StopPoint
        {
            get
            {
                return this.stopPointField;
            }
            set
            {
                this.stopPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ArrDateTime
        {
            get
            {
                return this.arrDateTimeField;
            }
            set
            {
                this.arrDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ArrIsTimingPoint
        {
            get
            {
                return this.arrIsTimingPointField;
            }
            set
            {
                this.arrIsTimingPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkDeviation
    {

        private GetJourneyResultJourneyRouteLinkDeviationDeviationScope[] deviationScopesField;

        private string publicNoteField;

        private string headerField;

        private string detailsField;

        private string summaryField;

        private string shortTextField;

        private int importanceField;

        private int influenceField;

        private int urgencyField;

        private GetJourneyResultJourneyRouteLinkDeviationWebLink[] webLinksField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DeviationScope", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetJourneyResultJourneyRouteLinkDeviationDeviationScope[] DeviationScopes
        {
            get
            {
                return this.deviationScopesField;
            }
            set
            {
                this.deviationScopesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PublicNote
        {
            get
            {
                return this.publicNoteField;
            }
            set
            {
                this.publicNoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShortText
        {
            get
            {
                return this.shortTextField;
            }
            set
            {
                this.shortTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Importance
        {
            get
            {
                return this.importanceField;
            }
            set
            {
                this.importanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Influence
        {
            get
            {
                return this.influenceField;
            }
            set
            {
                this.influenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Urgency
        {
            get
            {
                return this.urgencyField;
            }
            set
            {
                this.urgencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WebLink", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetJourneyResultJourneyRouteLinkDeviationWebLink[] WebLinks
        {
            get
            {
                return this.webLinksField;
            }
            set
            {
                this.webLinksField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkDeviationDeviationScope
    {

        private ScopeAttributeType[] scopeAttributeField;

        private System.DateTime fromDateTimeField;

        private System.DateTime toDateTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScopeAttribute", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ScopeAttributeType[] ScopeAttribute
        {
            get
            {
                return this.scopeAttributeField;
            }
            set
            {
                this.scopeAttributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime FromDateTime
        {
            get
            {
                return this.fromDateTimeField;
            }
            set
            {
                this.fromDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ToDateTime
        {
            get
            {
                return this.toDateTimeField;
            }
            set
            {
                this.toDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.etis.fskab.se/v1.0/ETISws")]
    public partial class GetJourneyResultJourneyRouteLinkDeviationWebLink
    {

        private string uRLField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }
    }
}
